# Generated by Django 4.0.4 on 2022-05-06 08:22

import basicpages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, validators=[basicpages.models.validate_name], verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, validators=[basicpages.models.validate_name], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
